spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ["http://localhost:3000"]
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowedHeaders: ["*"]
            allow-credentials: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true