server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/product_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

grpc:
  client:
    inventory-service:
      address: inventory-service:9090
      negotiation-type: plaintext

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakerevents

resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 2000ms
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 10s
      automaticTransitionFromOpenToHalfOpenEnabled: true
      registerHealthIndicator: true
  instances:
    # Circuit breaker for database calls within product-service
    productDbCircuitBreaker: # Example name for a DB circuit breaker
      baseConfig: default
      failureRateThreshold: 70 # Product DB might be critical, so trip faster